- refs #201   - Undone the changes made in r323     svn merge -c -323 http://svn.serverix/supose/trunk .
    Because the update has caused an error during
    the instrumenting phase of the build.
    org.apache.maven.surefire.booter.SurefireExecutionException: Invalid method Code length 
    69055 in class file com/soebes/supose/parse/java/JavaParser; nested exception is 
    java.lang.ClassFormatError: Invalid method Code length 69055 in class file com/soebes/supose/parse/java/JavaParser


git-svn-id: http://svn.serverix/supose/trunk@330 2a5690f4-4b40-0410-ba62-85a317ce182b